### ISSUE TITLE
Report tissue and p-values for eQTLs

### ISSUE THREAD

**Issue by wnewell** [Ensembl/postgap#82] opened 2017-05-16 16:08 UTC
e.g. in one column in STOPGAP: eqtl_tissue_pval_str:(AG(7.73e-06), AT(3.86e-08), BCBG(3e-06), BCo(7.25e-06), BFCB(6.57e-06), BMT(1.28e-05), CTF(1.92e-09), Lu(2.3e-09), SNSES(5.02e-07), SSELL(1.17e-06), Th(1.33e-13))

**Comment by dzerbino** [comment] 2017-05-16 16:41
Duplicate of #36

**Closed as completed by dzerbino** 2017-05-16 16:41 UTC
