### ISSUE TITLE
some additional resources to consider

### ISSUE THREAD

**Issue by elipapa** [Ensembl/postgap#21] opened 2016-11-15 11:07 UTC
Came across two more resources, which are potentially relevant for inclusion in the future?

http://metabolomics.helmholtz-muenchen.de/pgwas/index.php?task=locuslist

and

https://snipa.helmholtz-muenchen.de/snipa/?task=block_annotation

**Comment by dzerbino** [comment] 2016-11-17 10:33
Reading through the SNIPA paper, it is basically a duplicate of Ensembl REST services, but without the REST service component :/

pGWAS is a protein expression QTL dataset produced using a new technology (SOMAScan) that apparently produced 539 pQTLs (284 unique proteins, 84 451 independent SNPs) and was later analysed using SNIPA. This seems like a rather marginal dataset. In conclusion, interesting, but not top of the list.

**Closed as completed by dzerbino** 2016-11-17 10:33 UTC
Labels: enhancement, question
